name: Release Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '**'

# In Workflow B's YAML
  workflow_run:
    workflows: ["Build Main Workflow"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Install z88dk and Assemble Code
        run: |
          sudo snap install z88dk --beta
          sudo snap alias z88dk.z88dk-z80asm z88dk-z80asm
          make

      - name: Create Package Archive
        run: |
          tar cvf TRS-80-${{github.ref_name}}-ROM-Images.tar *.txt *.bin *.md

      # https://github.com/marketplace/actions/automatic-releases
      - name: Attach Package Archive
        uses: wwarthen/actions/packages/automatic-releases@built-packages
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          draft: true
          prerelease: true
          automatic_release_tag: "latest"
          title: "Build-${{github.ref_name}}"
          files: |
            *.tar
